export enum ProductStatus {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
  OUT_OF_STOCK = "OUT_OF_STOCK",
}



export enum ProductCategory {
  ELECTRONICS = "ELECTRONICS",
  MOBILE_PHONES = "MOBILE_PHONES",
  LAPTOPS = "LAPTOPS",
  TABLETS = "TABLETS",
  HEADPHONES = "HEADPHONES",
  CAMERAS = "CAMERAS",

  MEN_CLOTHING = "MEN_CLOTHING",
  WOMEN_CLOTHING = "WOMEN_CLOTHING",
  KIDS_CLOTHING = "KIDS_CLOTHING",
  SHOES = "SHOES",
  BAGS = "BAGS",

  WATCHES = "WATCHES",
  JEWELRY = "JEWELRY",
  BEAUTY = "BEAUTY",
  HOME_APPLIANCES = "HOME_APPLIANCES",
  FURNITURE = "FURNITURE",
  SPORTS = "SPORTS",
  BOOKS = "BOOKS",
  GROCERIES = "GROCERIES",
  ACCESSORIES = "ACCESSORIES",
}